### ISSUE TITLE
[Release-1.0] Restructure the project

### ISSUE THREAD

**Issue by isabellabrookes** [PixelogicDev/Gruvee-Mobile#6]
File structure is messy. 

Need a way to flatten/streamline the project.

I believe we have some ideas on discord, let's collate them here.

**Comment by isabellabrookes** [comment]
@tjengland 's suggestion
```
src/
  -api/
  -components/
     -atoms/
     -molecules/
     -organisms/
     -pages/
  -utils/
  -config/
     -navigation/
assets/res whatever you want to call static, shared resources/
  -icons/
  -images/
  -fonts/
android/
ios/
```

**Comment by creativenobu** [comment]
It would be great to do this before the project gets complex later on. If there is no one wanting to do it, perhaps I could tackle this?

I can take a look at some suggested project structure for a react native project. Or I can implement the project structure that was suggested by @tjengland

**Comment by isabellabrookes** [comment]
@creativenobu research is always appreciated. Multiple options are better than one. 

I'm wondering if it's worth waiting until Release-1.0 is complete before restructuring/refactoring.

**Comment by creativenobu** [comment]
It would be best to do it before release since after that, refactoring and restructuring would be a pain. Anyway, I found 3 great project structures we can use. I like the first proposal since it is a detailed structure and we can keep components separate from page views.

## Proposal 1 - [ReactNative.guide](https://www.reactnative.guide/5-project-structure-and-start-building-some-app/5.1-customising-the-structure.html)
```
.
├── __tests__
│   ├── ...
├── app
│   ├── assets
│   ├── config
│   ├── styles
│   ├── utils
│   ├── components
│   ├── pages
│   ├── routes
│   ├── redux
│   └── App.js
├── app.json
├── index.js
├── package.json
└── yarn.lock
```

-  `app/assets` - This is where all the images, videos, etc will go in.
- `app/config` - This is where configurations for the app will go in. For example, your environment specific config for dev and prod, etc.
- `app/styles` - This is where your global styles, themes, and mixins will go.
- `app/utils` - This is where all the services/utility files such as HTTP utility to make API calls, storage utility, data transformation utility, etc will go.
- `app/components` - The directory will contain all the dumb components. In short, these components will only do layouting and won't contain any states or business logic inside them. All the data to these components will be passed in as props. This concept will be explained in detail further in the book.
- `app/pages` - This directory will hold all the smart components. Smart components are those components which contain business logic and states in them. Their job is to pass the props to the dumb components after all the business logic has been executed.
- `app/routes` - This is where we will keep all our app's routing logic. This will contain the map between the pages(smart components) and the routes.
- `app/redux` - This will contain all our redux state management files like actions, reducers, store config, thunks etc.


## Proposal 2 - [React Native Log](https://medium.com/the-react-native-log/organizing-a-react-native-project-9514dfadaa0)
Very similar to the one above.

```
.
...
├── app
│   ├── config
│   ├── components
│   ├── lib
│   ├── screens
│   └── index.js
├── app.json
├── index.js
├── package.json
└── yarn.lock
```

- `app/config` - This directory aligns with our goal to Keep Configuration out of the Code. Like I mentioned earlier we’re going to keep anything that is used in multiple places throughout our app in one easy to access (and change) place. 
- `app/components` - This directory aligns with our goals of Maximum Code Reuse and Minimize Component State. In this directory we’ll be writing mostly functional components that can be used in multiple places throughout our app.
- `app/lib` - This directory aligns with our goal of Maximum Code Reuse and Cross Platform. We’re just keeping any general functions in here. In reality anything you think you’ll put in the app/lib/ directory can probably be found as an npm package.
- `app/screens` - This is the bread and butter of the app and aligns with our goal to Maximize Code Reuse and write Cross Platform. Typically an app is made up of a variety of screens (or routes/scenes, depending on your preference).
- `app/index.js` - Finally is the only file in our app directory and that serves as our entry point into our Cross Platform app. It allows us to require a single file from both index.ios.js and index.android.js and show the same thing on both platforms.

## Proposal 3 - [freeCodeCamp](https://www.freecodecamp.org/news/how-to-structure-your-project-and-manage-static-resources-in-react-native-6f4cfc947d92/)
A bit long, but it goes into details on structuring between a type-driven project or a feature-driven project (worth a read). It is a very android-biased structure.
```
.
...
├── src
│   ├── screens (like Login screen, Playlist screen, etc)
│   ├── library (for components, utils, storage, etc)
│   ├── res (resources, like assets folder but with const for color, strings, etc)
├── app.json
├── App.js
├── index.js
├── package.json
└── yarn.lock
```

Let me know you guys' thoughts on this. We can ask stream to help us out on this too :grin:

**Comment by adilanchian** [comment]
@creativenobu - THIS IS LIT. Great work thanks for the insight :). So I am between option 1 or 2, but I am definitely leaning towards 1. I like to make sure that all our business logic is under app and when we DO add tests. The one thing I'm iffy about are the Styles. I usually prefer to keep my styesheets with my components so maybe we can change that up

Either way, LETS GO WITH ONE. THANKS AGAIN.

**Comment by creativenobu** [comment]
Alright! We can always adjust where we want our business logic and presenter logic. I agree with no inclusion of `styles` directory.

I will start nagging you a lot on *what's what* in the project once I get started :grimacing: . So far we can agree on all logic within `app` except for bootstrapping, ie `index.js`?

```
.
├── app
│   ├── tests
│   ├── assets
│   ├── config
│   ├── utils
│   ├── components
│   ├── pages
│   ├── routes
│   ├── redux
│   └── App.js
├── app.json
├── index.js
├── package.json
└── yarn.lock
```

**Comment by adilanchian** [comment]
@creativenobu LETS GOOOO. This is awesome. Yes please nag me and lets get this done :). I'll do my best now to keep with this structure as the days go on...

Yes +1 logic within app. Also what does app.json refer to here?

**Comment by creativenobu** [comment]
That was just an example structure, I believe that's used for react native to identify the app name in the device. Since it is necessary, it would be best to just leave it in the root path.

On a side note, do you prefer folder names to be capitalized or prefer all in lower case (Not for file names)?

**Comment by adilanchian** [comment]
@creativenobu  - Yes sounds great friend. I think we should probably just do folders and filenames in lowercase, I'm not sure the best approach, but that seems good to me!

Also +1 on the app.json

**Comment by creativenobu** [comment]
Following up on the conversation from stream today, I think it would be best to keep them capitalized, too lazy to lowercase all of them :stuck_out_tongue:  React native files are capitalized which is for me, so it would be best to just follow their convention.

So directories will be **lowercased** and filenames according to react/react native conventions will be **capitalized**.

**Comment by creativenobu** [comment]
Here are the changes I've done:

+ Moved contants (`StyleContants.js`, `NavigationConstants.js` and `SocialConstants.js`) into the `config` directory
+ Added `index.js` for each component so that we don't have to call a component twice when importing (eg. to import Auth component we refer the path `Gruvee/components/Auth` instead of `Gruvee/components/Auth/Auth`

So far this is the current structure inside `app` directory (3-levels deep)

```
app/
├── App.js
├── assets
│   ├── buttons
│   │   └── add
│   ├── defaults
│   │   ├── album-artwork
│   │   └── playlist-image
│   └── icons
│       ├── members
│       ├── plus
│       ├── right-chevron
│       ├── social
│       └── trash
├── components
│   ├── Auth
│   │   ├── Auth.js
│   │   ├── components
│   │   └── index.js
│   ├── CommentsList
│   │   ├── CommentsList.js
│   │   ├── components
│   │   └── index.js
│   ├── common
│   │   ├── AddItemButton
│   │   ├── AnimatedSwipeRow
│   │   ├── CreateItemActionButton
│   │   ├── DynamicTextInput
│   │   ├── InputModal
│   │   ├── ShowMembersAction
│   │   └── SwipeAction
│   ├── MembersSideMenu
│   │   ├── index.js
│   │   └── MembersSideMenu.js
│   ├── Playlist
│   │   ├── components
│   │   ├── index.js
│   │   └── Playlist.js
│   ├── ReduxProvider
│   │   ├── index.js
│   │   └── ReduxProvider.js
│   └── SongList
│       ├── components
│       ├── index.js
│       └── SongList.js
├── config
│   ├── navigation.js
│   ├── social.js
│   └── styles.js
├── lib
│   ├── Playlist.js
│   ├── SongComment.js
│   └── Song.js
├── mock
│   ├── members.js
│   ├── playlists.js
│   ├── songComments.js
│   ├── songs.js
│   ├── spotifyFindResponse.js
│   └── user.js
└── redux
    ├── actions
    │   ├── ActionsType.js
    │   ├── comments
    │   ├── members
    │   ├── playlists
    │   ├── songs
    │   └── user
    ├── helpers
    │   └── logger.js
    ├── reducers
    │   ├── CommentsDataReducer.js
    │   ├── index.js
    │   ├── MembersDataReducer.js
    │   ├── PlaylistsDataReducer.js
    │   ├── SongsDataReducer.js
    │   └── UserDataReducer.js
    └── selectors
        ├── CommentsSelector.js
        ├── MembersSelector.js
        ├── PlaylistsSelector.js
        └── SongsSelector.js
```

**Comment by creativenobu** [comment]
I would also like to involve #28 into the mix, since they both go hand-in-hand

**Comment by adilanchian** [comment]
Overall, this is perfect. It definitely seems a lot more organized. Here a few thoughts that I had:

- I feel as though we should rename the folder inside components, called `components` to something else like `subcomponents` or `partials`. Or is it even necessary?
- Just a nit thing here: `common` should be capitalized (just in case this was a typo)
- We should not use any Kebab Syntax in here. Should all be camel case

EXCITED.

**Comment by creativenobu** [comment]
> I feel as though we should rename the folder inside components, called components to something else like subcomponents or partials. Or is it even necessary?

I don't think it would be necessary. We can keep the inner `components` name and use them only inside the current main component. If these inner components are required by other main components then we just move them to the `common` components directory.

> Just a nit thing here: common should be capitalized (just in case this was a typo)

No that was not a typo, because `common` is not a component itself but holds components that would be required by other components. If you still want then I can change it to `Common`, I just want to let you and anyone else contributing have a familiarity with the project structure.

> We should not use any Kebab Syntax in here. Should all be camel case

I used `kebab-case` only on assets since they are not really "class" or "business logic code", I would actually prefer `snake_case` for these vs `CamelCase` (eg `album-artwork` can become `album_artwork` and not `AlbumArtwork`. But that's just personal preference (I use linux, so the UNIX way has affected me haha)

**Comment by adilanchian** [comment]
> I don't think it would be necessary. We can keep the inner components name and use them only inside the current main component. If these inner components are required by other main components then we just move them to the common components directory.
- Ya it's hard to say without going through the process of using the code you know? Like actually navigating through. I think you're right now. Let's keep it as you suggested!

>No that was not a typo, because common is not a component itself but holds components that would be required by other components. If you still want then I can change it to Common, since familiarity with the project structure is more crucial than just nit-pick letter casing.
- Good context here, thanks! Let's try to keep it as consistent with guidelines as possible

> I used kebab-case only on assets since they are not really "class" or "business logic code", I would actually prefer snake_case for these vs CamelCase (eg album-artwork can become album_artwork and not AlbumArtwork. But that's just personal preference (I use linux, so the UNIX way has affected me haha)
- Definitely use snake case for these guys haha. I like it much more than kebab!


Looking awesome man. Thanks for this!

**Comment by creativenobu** [comment]
Changed from `kebeb-case` to `snake_case` for assets directory and file names. Overall view of the `app/` directory:

```
app/
├── App.js
├── assets
│   ├── buttons
│   │   └── add/
│   ├── defaults
│   │   ├── album_artwork
│   │   └── playlist_image
│   └── icons
│       ├── members/
│       ├── plus/
│       ├── right_chevron/
│       ├── social/
│       └── trash/
├── components
│   ├── Auth
│   │   ├── Auth.js
│   │   ├── components/
│   │   └── index.js
│   ├── CommentsList
│   │   ├── CommentsList.js
│   │   ├── components/
│   │   └── index.js
│   ├── common
│   │   ├── AddItemButton
│   │   ├── AnimatedSwipeRow
│   │   ├── CreateItemActionButton
│   │   ├── DynamicTextInput
│   │   ├── InputModal
│   │   ├── ShowMembersAction
│   │   └── SwipeAction
│   ├── MembersSideMenu
│   │   ├── index.js
│   │   └── MembersSideMenu.js
│   ├── Playlist
│   │   ├── components/
│   │   ├── index.js
│   │   └── Playlist.js
│   ├── ReduxProvider
│   │   ├── index.js
│   │   └── ReduxProvider.js
│   └── SongList
│       ├── components/
│       ├── index.js
│       └── SongList.js
├── config
│   ├── navigation.js
│   ├── social.js
│   └── styles.js
├── lib
│   ├── Playlist.js
│   ├── SongComment.js
│   └── Song.js
├── mock
│   ├── members.js
│   ├── playlists.js
│   ├── songComments.js
│   ├── songs.js
│   ├── spotifyFindResponse.js
│   └── user.js
└── redux
    ├── actions
    │   ├── ActionsType.js
    │   ├── comments/
    │   ├── members/
    │   ├── playlists/
    │   ├── songs/
    │   └── user/
    ├── helpers
    │   └── logger.js
    ├── reducers
    │   ├── CommentsDataReducer.js
    │   ├── index.js
    │   ├── MembersDataReducer.js
    │   ├── PlaylistsDataReducer.js
    │   ├── SongsDataReducer.js
    │   └── UserDataReducer.js
    └── selectors
        ├── CommentsSelector.js
        ├── MembersSelector.js
        ├── PlaylistsSelector.js
        └── SongsSelector.js
```

**Comment by adilanchian** [comment]
This ^^^
freaking awesome

**Comment by adilanchian** [comment]
WE MERGED IT. THANKS FRIEND
